name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build:docker

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Log in to Yandex Container Registry
        run: echo "${{ secrets.YCR_TOKEN }}" | docker login cr.yandex -u oauth --password-stdin
      - name: Push to Yandex Container Registry
        run: |
          docker tag shri-infra cr.yandex/<идентификатор_реестра>/app:${{ github.run_number }}
          docker tag shri-infra cr.yandex/<идентификатор_реестра>/app:${{ github.run_number }}_latest
          docker push cr.yandex/<идентификатор_реестра>/app:${{ github.run_number }}
          docker push cr.yandex/<идентификатор_реестра>/app:${{ github.run_number }}_latest
      - name: Create Release Tag
        run: |
          git tag -a v${{ github.run_number }} -m "Release ${{ github.run_number }}"
          git push origin --tags
      - name: Create Issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Release ${{ github.run_number }}
          body: |
            **Дата:** ${{ github.event.date }}
            **Автор релиза:** ${{ github.actor }}
            **Номер версии:** ${{ github.run_number }}
            **Коммиты:**
            ${{ github.event.commits }}
            **Docker образ:**
            cr.yandex/<идентификатор_реестра>/app:${{ github.run_number }}
