name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'
      - run: npm install
      - run: npm run lint
      - run: npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: lint_and_test

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'
      - run: npm install
      - run: npm run build
      - name: Build Docker image
        run: docker build . -t shri-infra:latest
      - name: Log in to Yandex Container Registry
        run: echo "${{ secrets.YCR_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Tag and Push Docker images to Yandex Container Registry
        run: |
          docker tag shri-infra:latest cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.run_number }}
          docker tag shri-infra:latest cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.run_number }}_latest
          docker push cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.run_number }}
          docker push cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.run_number }}_latest
      - name: Set up Git user
        run: |
          git config --global user.email "ph.kirilltsvetkov@yandex.ru"
          git config --global user.name "Kirill"
      - name: Create Release Tag
        run: |
          git tag -a v${{ github.run_number }} -m "Release ${{ github.run_number }}"
          git push origin --tags
      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          assignees: ""
          labels: release

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Check if image exists in Yandex Container Registry
        run: |
          if ! docker manifest inspect cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.run_number }}_latest; then
            echo "Image not found!" && exit 1
          fi

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: SSH and deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Logging in to Yandex Container Registry"
            echo "${{ secrets.YCR_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
            echo "Pulling the latest Docker image"
            docker pull cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.run_number }}_latest
            echo "Stopping and removing old container"
            docker stop my_app_container || true
            docker rm my_app_container || true
            echo "Running the new Docker image"
            docker run -d --name my_app_container -p 3000:3000 cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.run_number }}_latest

      - name: Update Issue with deployment information
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all
