name: Create Release

on: workflow_dispatch

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'
      - run: npm install
      - run: npm run lint
      - run: npm test

  create_release_branch:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get current run number
        id: run-number
        run: echo "run_number=${{ github.run_number }}" >> $GITHUB_ENV
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

  create_release_docker:
    runs-on: ubuntu:latest
    needs: create_release_branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: releases/${{ github.run_number }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'
      - run: |
          npm install
          npm run build
